apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: adaptive-controller
  namespace: sockshop
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
