apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sockshop
  labels:
    app: front-end
    app.kubernetes.io/part-of: sockshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: front-end
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:8080"
            - "-text=Sock Shop front-end"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: sockshop
  labels:
    app: catalogue
    app.kubernetes.io/part-of: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: catalogue
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:8080"
            - "-text=Sock Shop catalogue"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: sockshop
  labels:
    app: carts
    app.kubernetes.io/part-of: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
        - name: carts
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:8080"
            - "-text=Sock Shop carts"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
